#!/usr/bin/env perl
# nes-diff -- compare debug output to nestest

use v5.10;
use warnings;
use strict;

use IO::All qw(io);

my $txt_output = shift || die "need an input file";
my $nestest_output = shift || "doc/nestest.log";

my @txt = io->file($txt_output)->chomp->getlines;
my @nestest = io->file($nestest_output)->chomp->getlines;

# ignore the cruft I output at the top of my log
while ($txt[0] !~ /^[0-9A-Fa-f]{4}/) {
	shift @txt;
}

my $i = 0;
while (($i < @txt) and ($i < @nestest)) {
	my $txt = $txt[$i];
	my ($txt_pc)  = $txt =~ /^([0-9A-F]{4}) /;
	my ($txt_a)   = $txt =~ / (A:[0-9A-f]{2}) /;
	my ($txt_x)   = $txt =~ / (X:[0-9A-f]{2}) /;
	my ($txt_y)   = $txt =~ / (Y:[0-9A-f]{2}) /;
	my ($txt_p)   = $txt =~ / (P:[0-9A-f]{2}) /;
	my ($txt_sp)  = $txt =~ / (SP:[0-9A-f]{2}) /;
	my ($txt_cyc) = $txt =~ / (CYC:\s*[0-9]{1,3})$/;
	my $txt_data = join ' ', $txt_pc, $txt_a, $txt_x, $txt_y, $txt_p, $txt_sp, $txt_cyc;

	my $nes = $nestest[$i];
	my ($nes_pc)  = $nes =~ /^([0-9A-F]{4}) /;
	my ($nes_a)   = $nes =~ / (A:[0-9A-f]{2}) /;
	my ($nes_x)   = $nes =~ / (X:[0-9A-f]{2}) /;
	my ($nes_y)   = $nes =~ / (Y:[0-9A-f]{2}) /;
	my ($nes_p)   = $nes =~ / (P:[0-9A-f]{2}) /;
	my ($nes_sp)  = $nes =~ / (SP:[0-9A-f]{2}) /;
	my ($nes_cyc) = $nes =~ / (CYC:\s*[0-9]{1,3})$/;
	my $nes_data = join ' ', $nes_pc, $nes_a, $nes_x, $nes_y, $nes_p, $nes_sp, $nes_cyc;

	if ($txt_data ne $nes_data) {
		my $idx = $i + 1;
		say "$idx - $nes_data";
		say "$idx + $txt_data";
		last;
	}

	$i += 1;
}
