#!/usr/bin/env perl
# nes-flags -- processor flag dump
# usage: nes-flags <hex> [<hex>, ...]

use v5.10;
use warnings;
use strict;

die "args needed" unless @ARGV > 0;

say "      sv__dizc";
for (@ARGV) {
	die "bad hex string: $_" unless /^[0-9a-f]+$/i;
	printf "0x$_: %08b\n", hex $_;
}
