use addr::AddressingMode;
use cpu::CPU;

#[derive(Debug)]
pub enum Instruction {
    None,
    ADC,
    ANC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DCP,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LAX,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SAX,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
}

impl Instruction {
    pub fn run(&self, cpu: &mut CPU, addr: u16, val: u8, addr_mode: &AddressingMode) {
        match *self {
            Instruction::ADC => cpu.adc(addr, val),
            Instruction::ANC => cpu.anc(addr, val),
            Instruction::AND => cpu.and(addr, val),
            Instruction::ASL => cpu.asl(addr, val, addr_mode),
            Instruction::BCC => cpu.bcc(addr, val),
            Instruction::BCS => cpu.bcs(addr, val),
            Instruction::BEQ => cpu.beq(addr, val),
            Instruction::BIT => cpu.bit(addr, val),
            Instruction::BMI => cpu.bmi(addr, val),
            Instruction::BNE => cpu.bne(addr, val),
            Instruction::BPL => cpu.bpl(addr, val),
            Instruction::BVC => cpu.bvc(addr, val),
            Instruction::BVS => cpu.bvs(addr, val),
            Instruction::CLC => cpu.clc(addr, val),
            Instruction::CLD => cpu.cld(addr, val),
            Instruction::CLV => cpu.clv(addr, val),
            Instruction::CMP => cpu.cmp(addr, val),
            Instruction::CPX => cpu.cpx(addr, val),
            Instruction::CPY => cpu.cpy(addr, val),
            Instruction::DCP => cpu.dcp(addr, val),
            Instruction::DEC => cpu.dec(addr, val),
            Instruction::DEX => cpu.dex(addr, val),
            Instruction::DEY => cpu.dey(addr, val),
            Instruction::EOR => cpu.eor(addr, val),
            Instruction::INC => cpu.inc(addr, val),
            Instruction::INX => cpu.inx(addr, val),
            Instruction::INY => cpu.iny(addr, val),
            Instruction::JMP => cpu.jmp(addr, val),
            Instruction::JSR => cpu.jsr(addr, val),
            Instruction::LAX => cpu.lax(addr, val),
            Instruction::LDA => cpu.lda(addr, val),
            Instruction::LDX => cpu.ldx(addr, val),
            Instruction::LDY => cpu.ldy(addr, val),
            Instruction::LSR => cpu.lsr(addr, val, addr_mode),
            Instruction::NOP => cpu.nop(addr, val),
            Instruction::ORA => cpu.ora(addr, val),
            Instruction::PHA => cpu.pha(addr, val),
            Instruction::PHP => cpu.php(addr, val),
            Instruction::PLA => cpu.pla(addr, val),
            Instruction::PLP => cpu.plp(addr, val),
            Instruction::ROL => cpu.rol(addr, val, addr_mode),
            Instruction::ROR => cpu.ror(addr, val, addr_mode),
            Instruction::RTI => cpu.rti(addr, val),
            Instruction::RTS => cpu.rts(addr, val),
            Instruction::SAX => cpu.sax(addr, val),
            Instruction::SBC => cpu.sbc(addr, val),
            Instruction::SEC => cpu.sec(addr, val),
            Instruction::SED => cpu.sed(addr, val),
            Instruction::SEI => cpu.sei(addr, val),
            Instruction::STA => cpu.sta(addr, val),
            Instruction::STX => cpu.stx(addr, val),
            Instruction::STY => cpu.sty(addr, val),
            Instruction::TAX => cpu.tax(addr, val),
            Instruction::TAY => cpu.tay(addr, val),
            Instruction::TSX => cpu.tsx(addr, val),
            Instruction::TXA => cpu.txa(addr, val),
            Instruction::TXS => cpu.txs(addr, val),
            Instruction::TYA => cpu.tya(addr, val),
            _ => panic!("unsupported instruction {:?}", *self),
        }
    }
}
